
version: '3.9'

# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "5678:5678"  # Debugger port
    environment:
      DEBUG: "True"
      LOG_LEVEL: "DEBUG"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
  frontend:
    build:
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
