
site_name: GREDs AI Reference Library
site_description: Documentation for the GREDs AI Reference Library system
site_author: Nicolas Brett
repo_url: https://github.com/nbbulk-dotcom/COSMOLOGY
repo_name: nbbulk-dotcom/COSMOLOGY

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference: api-reference.md
  - User Guide: user-guide.md
  - Deployment: deployment.md

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings
